[package]
name = "augur-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
hdf5 = ["dep:hdf5"]

[dependencies]
augur-event-types.workspace = true
crossbeam-channel.workspace = true
evt3-core.workspace = true
gethostname.workspace = true
hdf5 = { workspace = true, optional = true }
serde.workspace = true
thiserror.workspace = true
time.workspace = true
toml.workspace = true
